onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /i2c_master_single_byte_TB/r_Clock
add wave -noupdate /i2c_master_single_byte_TB/r_Reset
add wave -noupdate /i2c_master_single_byte_TB/r_Wr_Start
add wave -noupdate /i2c_master_single_byte_TB/r_Rd_Start
add wave -noupdate /i2c_master_single_byte_TB/r_Wr_Byte
add wave -noupdate /i2c_master_single_byte_TB/w_Rd_Byte
add wave -noupdate /i2c_master_single_byte_TB/w_Busy
add wave -noupdate /i2c_master_single_byte_TB/w_Error
add wave -noupdate /i2c_master_single_byte_TB/w_SCL
add wave -noupdate /i2c_master_single_byte_TB/w_SDA
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/i_Clk
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/i_Rst
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/i_Enable
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/i_Slave_Addr
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/i_Wr_Start
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/i_Rd_Start
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/i_Wr_Byte
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/o_Busy
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/o_Rd_Byte
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/o_Error
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/io_scl
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/io_sda
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/w_sck_en
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/w_sda_en
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/w_Arb_Lost
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/w_Cmd_Ack
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/w_Slave_Ack
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/r_Cmd_Start
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/r_Cmd_Stop
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/r_Wr_Cmd
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/r_Rd_Cmd
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/r_Cmd_Byte
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/r_Wr_Byte
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/r_Cmd_Ack
add wave -noupdate -radix decimal /i2c_master_single_byte_TB/I2C_M_test/r_SM_Main
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/o_Done
add wave -noupdate /i2c_master_single_byte_TB/I2C_slave/scl
add wave -noupdate /i2c_master_single_byte_TB/I2C_slave/sda
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/clk
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/rst
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/nReset
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/ena
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/clk_cnt
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/start
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/stop
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/read
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/write
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/ack_in
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/din
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/cmd_ack
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/ack_out
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/i2c_busy
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/i2c_al
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/dout
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/scl_i
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/scl_o
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/scl_oen
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/sda_i
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/sda_o
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/sda_oen
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/core_cmd
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/core_txd
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/core_ack
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/core_rxd
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/sr
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/shift
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/ld
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/go
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/dcnt
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/cnt_done
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/c_state
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/clk
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/rst
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/nReset
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/ena
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/clk_cnt
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/cmd
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/cmd_ack
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/busy
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/al
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/din
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/dout
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/scl_i
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/scl_o
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/scl_oen
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/sda_i
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/sda_o
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/sda_oen
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/cSCL
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/cSDA
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/fSCL
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/fSDA
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/sSCL
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/sSDA
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/dSCL
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/dSDA
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/dscl_oen
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/sda_chk
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/clk_en
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/slave_wait
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/cnt
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/filter_cnt
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/c_state
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/scl_sync
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/sta_condition
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/sto_condition
add wave -noupdate /i2c_master_single_byte_TB/I2C_M_test/byte_controller/bit_controller/cmd_stop
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {117920640 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 416
configure wave -valuecolwidth 40
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {421312500 ps}
